# Generated by Django 2.2.10 on 2020-03-29 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('customer', '0001_initial'),
        ('core', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_booking',
            name='coupon_applied',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer_promotional'),
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ride_booking'),
        ),
        migrations.AddField(
            model_name='location',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.city'),
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ride_booking'),
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendor.vendor_cars'),
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendor.driver'),
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vendor.vendorprofile'),
        ),
        migrations.AddField(
            model_name='expected_time_hault',
            name='ride_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ride_types'),
        ),
        migrations.AddField(
            model_name='city',
            name='ride_types',
            field=models.ManyToManyField(to='core.ride_types'),
        ),
        migrations.AddField(
            model_name='car_attr_comparison',
            name='attr_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car_attr'),
        ),
        migrations.AddField(
            model_name='car_attr_comparison',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.car_types'),
        ),
        migrations.AddField(
            model_name='calc_city_attr_value',
            name='attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.calc_attr'),
        ),
        migrations.AddField(
            model_name='calc_city_attr_value',
            name='car_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.car_types'),
        ),
        migrations.AddField(
            model_name='calc_city_attr_value',
            name='city1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='city1', to='core.city', verbose_name='Pickup City'),
        ),
        migrations.AddField(
            model_name='calc_city_attr_value',
            name='city2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='city2', to='core.city', verbose_name='Drop City'),
        ),
        migrations.AddField(
            model_name='assign_vendor',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ride_booking'),
        ),
        migrations.AddField(
            model_name='assign_vendor',
            name='vendors',
            field=models.ManyToManyField(to='vendor.vendorprofile'),
        ),
        migrations.AddField(
            model_name='airport',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.city'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
