# Generated by Django 2.2.10 on 2020-03-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200329_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='popular_destinations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_place', models.CharField(max_length=104)),
                ('to_place', models.CharField(max_length=104)),
                ('popular_place', models.CharField(max_length=104)),
                ('distance', models.PositiveSmallIntegerField()),
                ('starting_from_price', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Popular Destinations',
            },
        ),
    ]
