# Generated by Django 2.2.10 on 2020-04-06 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0001_initial'),
        ('core', '0003_popular_destinations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='final_ride_detail',
            name='vendor',
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='core.vendorbids'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorbids',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendorprofile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assign_vendor',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ride_booking'),
        ),
        migrations.AlterField(
            model_name='final_ride_detail',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='core.ride_booking'),
        ),
        migrations.AlterField(
            model_name='final_ride_detail',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendor.vendor_cars'),
        ),
        migrations.AlterField(
            model_name='final_ride_detail',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='vendor.driver'),
        ),
        migrations.AlterField(
            model_name='vendorbids',
            name='max_bid',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
