# Generated by Django 2.2.10 on 2020-04-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200406_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='mobile',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
