# Generated by Django 2.2 on 2020-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contact_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_booking',
            name='ride_status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=10),
        ),
    ]
