# Generated by Django 2.2 on 2020-04-30 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20200430_1542'),
        ('core', '0006_auto_20200430_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride_booking',
            old_name='ride_end_datetime',
            new_name='drop_datetime',
        ),
        migrations.RenameField(
            model_name='ride_booking',
            old_name='ride_start_datetime',
            new_name='pickup_datetime',
        ),
        migrations.RemoveField(
            model_name='ride_booking',
            name='coupon_applied',
        ),
        migrations.RemoveField(
            model_name='ride_booking',
            name='ride_fare',
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='additional_charges',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='additional_choices',
            field=models.ManyToManyField(to='core.ride_choices'),
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='advance',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='balance_used',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='car_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.car_types'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='customer.customer_promotional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='early_pickup_charges',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='exact_drop',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='exact_pickup',
            field=models.CharField(default=0, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='final_fare',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='gst_charges',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='inital_charges',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='late_drop_charges',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='night_charges',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='ride_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.ride_types'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='drop',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='extra_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='final_ride_fare',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='pickup',
            field=models.CharField(max_length=512),
        ),
    ]
