# Generated by Django 2.2 on 2020-04-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200430_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_booking',
            name='additional_hault',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='additional_pickup',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='addtional_drop',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
