# Generated by Django 2.2 on 2020-05-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200430_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_booking',
            name='additional_hault',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='additional_pickup',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='addtional_drop',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
