# Generated by Django 2.2 on 2020-05-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200509_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_booking',
            name='balance_used',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customer.customer_promotional'),
        ),
    ]
