# Generated by Django 2.2 on 2020-05-29 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200525_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_booking',
            name='drop_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='drop_city', to='core.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride_booking',
            name='pickup_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='pickup_city', to='core.city'),
            preserve_default=False,
        ),
    ]
