# Generated by Django 2.2 on 2020-06-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200529_0624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendorbids',
            name='max_bid',
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='collected_amount',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='final_odometer_reading',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='initial_odometer_reading',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='other_charges',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendorbids',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='ride_status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Rejected', 'Rejected'), ('Selected Vendors', 'Selected Vendors'), ('Assigned Vendor', 'Assigned Vendor'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=16),
        ),
    ]
