# Generated by Django 2.2 on 2020-06-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20200611_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorbids',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
