# Generated by Django 2.2 on 2020-07-02 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200618_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotional_code', models.CharField(max_length=10)),
                ('referralbenefit', models.IntegerField(verbose_name='Amount to be credited to the person using it')),
                ('customerbenefit', models.IntegerField(verbose_name='Amount to be credited to the customer referring')),
                ('is_activated', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='User to assign the referral code to')),
            ],
            options={
                'verbose_name_plural': 'User Referral Codes',
            },
        ),
    ]
