# Generated by Django 2.2 on 2020-07-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_user_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_booking',
            name='exact_drop',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='exact_pickup',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
