# Generated by Django 2.2 on 2020-07-24 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20200724_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_booking',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
