# Generated by Django 2.2 on 2020-07-24 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ride_booking_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='final_ride_detail',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='final_ride_detail',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_ride_detail',
            name='collected_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_ride_detail',
            name='final_odometer_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_ride_detail',
            name='initial_odometer_reading',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='final_ride_detail',
            name='other_charges',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
