# Generated by Django 2.2 on 2020-07-26 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200724_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_booking',
            name='ride_status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Rejected', 'Rejected'), ('Selected Vendors', 'Selected Vendors'), ('Assigned Vendor', 'Assigned Vendor'), ('Assigned Car/Driver', 'Assigned Car/Driver'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], max_length=16),
        ),
    ]
