# Generated by Django 2.2 on 2020-08-03 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20200726_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='final_ride_detail',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_ride_detail', to='core.ride_booking'),
        ),
        migrations.AlterField(
            model_name='ride_booking',
            name='ride_status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Rejected', 'Rejected'), ('Selected Vendors', 'Selected Vendors'), ('Assigned Vendor', 'Assigned Vendor'), ('Assigned Car/Driver', 'Assigned Car/Driver'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Verified', 'Verified'), ('Cancelled', 'Cancelled')], max_length=32),
        ),
    ]
