# Generated by Django 2.2 on 2020-08-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20200803_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_booking',
            name='price_kkm',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
