# Generated by Django 2.2 on 2020-08-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_ride_booking_price_kkm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride_booking',
            old_name='price_kkm',
            new_name='price_km',
        ),
    ]
