# Generated by Django 2.2 on 2020-09-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20200804_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_booking',
            name='additional_choices',
            field=models.ManyToManyField(null=True, to='core.ride_choices'),
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('name', 'state')},
        ),
    ]
