# Generated by Django 2.2.10 on 2020-03-29 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_promotional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotional_code', models.CharField(max_length=10)),
                ('referralbenefit', models.IntegerField(verbose_name='Amount to be credited to the person using it')),
                ('customerbenefit', models.IntegerField(verbose_name='Amount to be credited to the customer referring')),
                ('is_activated', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Customer Promotional Codes',
            },
        ),
        migrations.CreateModel(
            name='referrals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.customer_promotional')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Promotional Code Used',
            },
        ),
        migrations.CreateModel(
            name='customerprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('father_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('dob', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('contact1', models.CharField(max_length=10)),
                ('contact2', models.CharField(blank=True, max_length=10, null=True)),
                ('street_1', models.CharField(max_length=100)),
                ('street_2', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=6)),
                ('pancard', models.FileField(blank=True, null=True, upload_to='')),
                ('aadharcard_front', models.FileField(blank=True, null=True, upload_to='')),
                ('aadharcard_rear', models.FileField(blank=True, null=True, upload_to='')),
                ('votercard', models.FileField(blank=True, null=True, upload_to='')),
                ('driving_licence_front', models.FileField(blank=True, null=True, upload_to='')),
                ('driving_licence_rear', models.FileField(blank=True, null=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Customer Details',
            },
        ),
        migrations.AddField(
            model_name='customer_promotional',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customerprofile', verbose_name='Customer to assign the referral code to'),
        ),
    ]
