# Generated by Django 2.2 on 2020-04-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerprofile',
            old_name='contact1',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='contact2',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='father_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='state',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='street_1',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='street_2',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
